### ISSUE TITLE
Question with "-"

### ISSUE THREAD

**Issue by philg1234** [aznamingtool/AzureNamingTool#10]
Hello,

i would like to use this Azure Naming Tools for our Customers.
Now a short Question:

Is it possible to use "-" between the Naming blocks?

So at the moment we have vor example a vm with:

vmsqlweu01

can i change the Naming Tool app to give me this Name with "-":
vm-sql-weu-01

Thanks a lot.

Regards,
Phil

**Comment by BryanSoltis** [comment]
Hi @philg1234,

Thank you for your feedback. The Azure Naming Tool allows you to use 4 different delimiters to go in between your components. When logged in as the Admin, go to the Configuration and select the desired delimiter.

<img width="725" alt="image" src="https://github.com/aznamingtool/AzureNamingTool/assets/13591910/8427f68a-b7d6-49a8-8c43-f1faa3437e0e">

The tool will use this delimiter in between your components. In the event a resource type does not allow the selected delimiter, it will be removed.

Hope this helps!

-Bryan

**Comment by philg1234** [comment]
Hi @BryanSoltis,

thanks a lot for your fast Answer.
Perfect.

Very nice Tool.

Regards,
Phil
